#!/bin/bash -e

# - params.sh файл генерируется zapusk-tool-ом в каталоге состояния
#   и в нем размещаются все параметры запуск-программы и их значения
# - текущий каталог для запуска скриптов [os] это каталог состояния
#   поэтому мы можем вызвать source params.sh

source params.sh

if test -z "$cronline"
then
  echo "cronline var is not defined!"
  exit 1 # ненулевой код возврата повлечет ошибку исполнения в zapusk-tool
fi

if test -z "$global_name"
then
  echo "global_name is blank!"
  exit 2
fi

echo "using global_name=$global_name"

cat <<TTT >"/etc/cron.d/zapusk_$global_name"
# generated by zapusk
SHELL=/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
$cronline
TTT

echo "generated cron file /etc/cron.d/zapusk_$global_name"
echo "**************"
cat "/etc/cron.d/zapusk_$global_name"
echo "**************"